var h = require('virtual-dom/h')
var vdom = require('vdom-virtualize').fromHTML
var layout = require('./layout')

module.exports = function (state) {
  return layout('about', state, [
    h('h1', 'About Sqebeqsed Stories'),
    h('div.about-text', vdom('<p>Welcome to the stories of Southeast Seattle’s Seward Park, home to the city’s last old-growth forest.</p><p>“Place is a story happening many times.” So say the Kwakiutl people of coastal British Columbia.</p><p>Seward Park is stories happening over and over, many at once. People come here to celebrate, congregate, meditate, race, run, walk, swim, climb, picnic, play, reflect, relax, make art, learn, unlearn, unwind. This place has sustained local residents for ten thousand years.</p><p>Before it was named “Seward Park” a century ago, this forested peninsula jutting into Lake Washington was known as “Sqebeqsed,” or “fat nose” in the local language, Lushootseed. And so Seward Park Stories are <b>Sqebeqsed Stories</b>.</p><p>Here, you will find stories about life in Sqebeqsed and the many lives that intersect with it, both human and non-human, present and past.</p><hr><p>Sqebeqsed Stories is created and curated by <a href="http://www.wendycall.com/">Wendy Call</a>, in collaboration with photographer <a href="http://www.thomasbancroft.com/">G. Thomas Bancroft</a>, researcher <a href="https://plu.academia.edu/ChristinaMontilla">Christina Montilla</a>, web developer <a href="http://sethvincent.com">Seth Vincent</a>, and many others who love Sqebeqsed. Made possible by an Individual Artist grant from <a href="http://www.4culture.org/">4Culture</a>, with in-kind support from <a href="http://www.sewardpark.org/index.html">Friends of Seward Park</a> and the <a href="http://sewardpark.audubon.org/">Seward Park Audubon Center</a>.</p><img src="assets/4culture.jpg">'))
  ])
}